set-up-and -mobile-version -skeleton
letarulinda/set-up-and-mobile-version-skeleton pull request #1
Opened 2022-05-27 22:40 UTC by letarulinda

-created HTML and CSS files for the project.
-Modified the README.md 
-Added Social Media Icons to the project
-Added gitworkflows to the project

2022-05-27 22:52 UTC, OmarRamoun requested changes
# 🟡 Almost There! 🏃

## Hi @letarulinda 👋

## Welcome to Microverse! 🌎

Good job so far! 👏. Your Code is Awesome! 💪

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃

## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Especially if that's is your first project 1️⃣. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better job** 💼.

_I am going to guide you on how to fix them down below. 🤓_


## Highlights 🌟

- ✔️ descriptive commit messages 
- ✔️ descriptive PR title and description
- ✔️ no linter errors

- The code is top-notch! 💯 and have a huge potential.

## Required Changes ♻️

_Check the comments under the review._

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.

## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@omarramoun](https://img.shields.io/github/followers/omarramoun?label=Ramoun&style=social)](https://github.com/omarramoun)
- This is My **Twitter**: [![@omarramoun](https://img.shields.io/twitter/follow/omarramoun?label=ramoun16&style=social)](https://twitter.com/omarramoun)
- This is My **Slack**: [![Ramoun](https://img.shields.io/badge/slack-@Ramoun-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-27 22:52 UTC, OmarRamoun commented on index.html
> +    <header>My Logo</header>
- [ ] [REQUIRED] Please, make sure to wrap the logo in a `<a>` tag as part of project requirments.

2022-05-27 22:52 UTC, OmarRamoun commented on index.html
> +  </body>
- [ ] [REQUIED] Please, add a section for the social media links as seen in the Figma Design

2022-05-27 22:52 UTC, OmarRamoun commented on index.css
> +}
- [ ] [REQUIRED] Please, add styles to the `index.css` file as requested in project requirements. Currently it has no styles

2022-05-28 01:29 UTC, Kossi-stack reviewed
Hi @letarulinda,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request
You have submitted a project, that have linters errors.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## 
_Invalid Code Review Request **does not count** into the code reviews limit._

2022-05-28 16:18 UTC, Ismailco requested changes
### Hi @letarulinda,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-28 16:18 UTC, Ismailco commented on index.html
> +        </h2>
- [ ] good work implementing the social links however you need to group them in a ``` ul``` and wrap every logo in a ```li``` tag, every logo should be a link so also kindly consider wrapping every ```img``` in a ```a``` tag so it's a link

2022-05-28 16:18 UTC, Ismailco commented on index.html
> +        <h2 class="social media links">
- [ ] [OPTIONAL] Please don't use ```hx``` to wrap element on your page, this is for the heading

2022-05-28 16:18 UTC, Ismailco commented on index.html
> +    <img src="assets/Union.jpg" alt="menu-bar" />
- [ ] [OPTIONAL] Please consider wraping the header section (nav bar/top bar) in a ```header``` tag, this is a requirement

2022-05-28 16:18 UTC, Ismailco commented on index.html
> +    <img src="assets/Union.jpg" alt="menu-bar" />
- [ ] [OPTIONAL] The hamburger button should have a ```nav``` tag, this is a requirement kindly implement it

2022-05-28 16:18 UTC, Ismailco commented on index.html
> +    <section class="intro-wrapper">
- [ ] [OPTIONAL] Kindly wrap the whole Headline section in ``` section``` tag not just the header (```h1```)

2022-05-28 16:18 UTC, Ismailco commented on index.css
> +body {
- [ ] Kindly consider styling your page according to the Figma design including the colors, margin/padding and align-items using flexbox. so your design is completed 

|Your design|Figma design|
|-|-|
|![Screenshot_20220528_171403](https://user-images.githubusercontent.com/25227022/170833739-fd73dd66-63f5-407d-af0f-48fecb98314f.png)|![Screenshot_20220528_171759](https://user-images.githubusercontent.com/25227022/170833774-3d680e0d-e3fd-4c3a-9778-533bb2971e24.png)|

2022-05-28 22:34 UTC, EricMbouwe approved these changes
Hi @letarulinda, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-28 22:40 UTC, merged